# Generated by Django 5.2.6 on 2025-09-14 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_delete_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 9, 14, 9, 29, 30, 387259, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('base', 'Base Card'), ('man_of_the_match', 'Man of the Match'), ('club_legend', 'Club Legend'), ('rising_star', 'Rising Star'), ('100_club', '100 Club'), ('limited_edition', 'Limited Edition'), ('signature_style', 'Signature Style'), ('hat_trick_hero', 'Hat-Trick Hero'), ('captain', 'Captain'), ('trophy_card', 'Trophy Card')], default='base', max_length=20),
        ),
    ]
